[WIP] Parse prerequisites in README
trussworks/prereqs pull request #9
Opened 2018-02-28 02:21 UTC by sansb

2018-02-28 02:27 UTC, sansb commented
Currently making a lot of assumptions about the README file. Mostly need to make this more robust.

2018-02-28 02:28 UTC, ferlatte requested changes
This is a cool start! I like the approach.

2018-02-28 02:28 UTC, ferlatte commented on prereqs
> +has_awk() {
Why not use has() instead of a new function for awk? I did that for curl in the update function, it seemed to be ok.

2018-02-28 02:28 UTC, ferlatte commented on prereqs
> +        # Get prereqs from README
I think this should be a separate function (prereqs_check_readme, perhaps?) so that it can be tested.

2018-02-28 02:28 UTC, ferlatte commented on prereqs
> +    has_awk
You only need awk if you're checking the README, so you should verify it there.

2018-02-28 02:28 UTC, ferlatte commented on prereqs
> +       -f         Specify a file to check for prereqs. Defaults to parsing README.md
Do we specify the README.md with -f, or the config file with -f?

2018-06-18 03:00 UTC, ferlatte commented
Hey @sansb check out PR #10 I think I got your parser ported with tests.

2018-09-13 23:34 UTC, ferlatte commented
Closing in favor of #10

2018-09-13 23:34 UTC, closed without merging